---
title: " My map "
author: "Luis Ambrocio"
date: "19/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

this map indicates the schools in which I have studied, as well as my favorite restaurants and bars

```{r}
library(leaflet)

iconFiles<-c("https://image.flaticon.com/icons/png/512/65/65968.png",
             "https://images.builderservices.io/s/cdn/v1.0/i/m?url=https%3A%2F%2Fstorage.googleapis.com%2Fproduction-hostgator-mexico-v1-0-7%2F577%2F302577%2FKQk9V2tg%2F96903503826a47fd8eddb3021a047c11&methods=resize%2C500%2C5000",
             "https://seeklogo.com/images/C/cch-unam-logo-DC9E094D02-seeklogo.com.png",
             "https://upload.wikimedia.org/wikipedia/commons/c/ca/Escudo-UNAM-escalable.svg",
             "https://upload.wikimedia.org/wikipedia/commons/c/ca/Escudo-UNAM-escalable.svg",
             "https://image.flaticon.com/icons/png/512/2195/2195416.png",
             "https://image.flaticon.com/icons/png/512/2195/2195416.png",
             "https://image.flaticon.com/icons/png/512/2195/2195416.png",
             "https://image.flaticon.com/icons/png/512/2195/2195416.png",
             "https://image.flaticon.com/icons/png/512/2195/2195416.png",
             "https://image.flaticon.com/icons/png/512/2195/2195416.png",
             "https://image.flaticon.com/icons/png/512/2195/2195416.png")

Icon <- makeIcon(
  iconUrl = iconFiles,
  iconWidth = 31*215/230, iconHeight = 31,
  iconAnchorX = 31*215/230/2, iconAnchorY = 16
)

linkspag<-c("Primaria Manuel María Contreras",
  "<a href='http://secundaria66.com/'>secundaria Vicente Guerrero</a>",
  "<a href='http://www.cch-naucalpan.unam.mx/'>CCH Naucalpan</a>",
  "<a href='https://www.acatlan.unam.mx/'>FES Acatlán</a>",
  "<a href='https://www.unamenlinea.unam.mx/recurso/instituto-de-investigaciones-en-matematicas-aplicadas-y-en-sistemas-iimas'>IIMAS UNAM</a>",
  "<a href='https://www.chilis.com.mx/'>Chili's satelite</a>",
  "<a href='https://labtk.com.mx/'>La BTK satelite</a>",
  "<a href='https://labtk.com.mx/'>La BTK Atizapan</a>",
  "<a href='https://www.facebook.com/TangerineOficiall'>Tangerine</a>",
  "<a href='https://www.facebook.com/latuba.atizapan.3/'>La tuba</a>",
  "<a href='https://www.facebook.com/Emojis-Bar-2021-101067798872977'>Emogis</a>",
  "Tacos el fogon"
)

LatLong <- data.frame(
  lat = c(19.61560930105004,19.613557000787182,19.474611112408653,19.482054176281483,19.319378700793727,19.525536777928693,
          19.513444452654824,19.559703478296253,19.548832038775508,19.54879159721112,19.482539674772624,19.516918635536307),
  lng = c(-99.29848449745224, -99.3169514159606, -99.24397208712625, -99.24450400247257, -99.18567354908657, -99.22742263623641,          -99.23280272945236, -99.24186406810074, -99.23921851410529, -99.23964766756995, -99.24202564121425,-99.21480346014523))

LatLong %>% 
  leaflet(options = leafletOptions(minZoom = 10)) %>%
  addTiles() %>%
  addMarkers(icon = Icon,clusterOptions = markerClusterOptions(),popup=linkspag)%>%
	addMiniMap(
		tiles = providers$Esri.WorldStreetMap,
		toggleDisplay = TRUE)

```

